id: I4784F93A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T00:18:59+00:00'
last_modified: '2022-06-09T06:19:56.973745+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20290
  title: ཀྲུང་གོའི་གཞི་རིམ་མང་ཚོགས་རངས་སྐྱོང་ལམ་ལུགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    10AA:
      image_group_id: I8LS20292
      title: Volume 1 of krung go'i gzhi rim mang tshogs rangs skyong lam lugs/
      total_pages: 213
      order: 1
      base_file: 10AA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
