id: P007132
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20290
  title: ཀྲུང་གོའི་གཞི་རིམ་མང་ཚོགས་རངས་སྐྱོང་ལམ་ལུགས།
  author: ''
  volumes:
    134c5288ddee4db5b5ea76893a30761b:
      image_group_id: I8LS20292
      title: ''
      volume_number: 1
      total_pages: 213
ebook_metadata:
  title: ཀྲུང་གོའི་གཞི་རིམ་མང་ཚོགས་རངས་སྐྱོང་ལམ་ལུགས།
  author: ''
  sku: P007132
  cover: cover.jpg
  layers:
  - pagination
